# Generated by Django 3.1.7 on 2021-07-28 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_virtual', models.BooleanField(default=False)),
                ('is_temporary', models.BooleanField(default=False)),
                ('last_four_digits', models.CharField(max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardIssuer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('minor_units', models.IntegerField()),
                ('iso_code', models.CharField(max_length=10)),
                ('symbol', models.CharField(max_length=10)),
                ('if_symbol_precedes_amount', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='EntityAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=255)),
                ('building_number', models.IntegerField()),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('type', models.CharField(choices=[('st', 'Street'), ('al', 'Alley'), ('nbhd', 'Neighborhood')], default='st', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EntityChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentProcessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ean_code', models.CharField(max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('amount_type', models.CharField(choices=[('pcs', 'Pieces'), ('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Milliliters'), ('l', 'Litres'), ('sec', 'Seconds'), ('min', 'Minutes'), ('hr', 'Hours'), ('mo', 'Months'), ('yr', 'Years'), ('pgs', 'Pages')], default='pcs', max_length=5)),
                ('category', models.CharField(choices=[('supp', 'Support'), ('food', 'Food'), ('earn', 'Earnings'), ('cent', 'Culture&entertainment'), ('elec', 'Electronics'), ('heal', 'Hygiene&health'), ('trvl', 'Transport&travel'), ('clth', 'Clothing'), ('othr', 'Other')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('balance', models.IntegerField()),
                ('type', models.CharField(choices=[('current', 'Current'), ('savings', 'Savings'), ('safe', 'Safe')], default='current', max_length=10)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='maggie.bank')),
                ('cards', models.ManyToManyField(to='maggie.Card')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='maggie.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('receipt_image', models.ImageField(upload_to='')),
                ('type', models.CharField(choices=[('pur', 'Purchase'), ('sub', 'Subscription'), ('gft', 'Gift'), ('sal', 'Salary'), ('don', 'Donation'), ('exc', 'Currency exchange'), ('tra', 'Money transfer'), ('cbk', 'Cashback or return'), ('oth', 'Other')], default='pur', max_length=3)),
                ('product', models.ManyToManyField(to='maggie.Product')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='maggie.entity')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='maggie_transaction_related', related_query_name='maggie_transactions', to='maggie.entity')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentWay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('payment_processor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='maggie.paymentprocessor')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('payment_way', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maggie.paymentway')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maggie.transaction')),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='maggie.vault')),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='maggie.entityaddress'),
        ),
        migrations.AddField(
            model_name='entity',
            name='chain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maggie.entitychain'),
        ),
        migrations.AddField(
            model_name='card',
            name='issuer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='maggie.cardissuer'),
        ),
    ]
