version: '3'

services:
  database:
    image: postgres:13.2
    ports:
      - "5432:5432"
    volumes:
      - maggie_db_data:/var/lib/postgresql/data
    env_file: .env

  backend:
    build: .
    command: bash -c "./wait-for-it.sh database:5432 && python3 ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - "database"
    restart: on-failure
    env_file: .env

volumes:
  maggie_db_data:
    external: true